# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|

  # --------------------------
  # config.vm
  # Vagrantが管理しているマシンの設定
  # --------------------------
  # ubuntu16.04を使用
  config.vm.box = "ubuntu/bionic64"
  # boxはURLを指定することで取得する
  config.vm.box_url = "https://cloud-images.ubuntu.com/xenial/current/xenial-server-cloudimg-amd64-vagrant.box"

  # ゲスト(vagrantのポート:3000)、ホスト(自分のPCのポート:3000)
  config.vm.network "forwarded_port", guest: 3000, host: 3001

  # ゲストOSの設定(デフォリトはLinux)
  # config.vm.guest = :linux

  # マシンのホスト名の設定(デフォルトはnil)
  # config.vm.hostname

  # マシンのネットワークの設定
  config.vm.network "private_network", ip: "192.168.33.10"

  # vagant up後のメッセージ
  config.vm.post_up_message = "Welcome to infratop!"

  # プロバイダの設定
  # config.vm.provider

  # ポートの衝突などを処理するために使用することができる、ポートの範囲を指定する。デフォルトでは2200から2250である。
  # config.vm.usable_port_range

  # --------------------------
  # config.ssh
  # VagrantがSSHを経由してマシンにどのようにアクセスするか設定する
  # --------------------------

  # vagrantにsshする際のユーザー名(デフォルトはvagrant)
  # config.ssh.username = vagrant

  # 仮想環境からhost(ローカル)の秘密鍵を使えるようになる
  # config.ssh.forward_agent = true

  # マシン上の同期フォルダを設定する。ホストマシン上のそのフォルダはゲストマシンとの間で同期される。
  # 複数フォルダを共有することも可能
  # デフォルト：/vagrant => /Users/ユーザー名/Desktop/作成したフォルダ/vagrant
  # config.vm.synced_folder "./", "/home/vagrant"

  # 利用する秘密鍵を指定
  # config.ssh.private_key_path = "~/.ssh/id_rsa"

  # config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
  #   vb.memory = "1024"
  # end

  # 秘密鍵と~/.ssh/configをvagrant内に移動する
  # config.vm.provision "file", source: "~/.ssh/id_rsa", destination: "~/id_rsa" #, mount_options: ["dmode=644","fmode=644"]
  # config.vm.provision "file", source: "~/.ssh/config", destination: "~/config"

  # root(sudo)で実行される
  config.vm.provision "shell", path: 'scripts/provision_root.sh'
  # vagrantユーザーで実行するスクリプト
  # config.vm.provision "shell", path: 'scripts/provision.sh', privileged: false

end
