module.exports = {
    // エラーメッセージ(A-Z順)-----------------------------------------//
    about_button: '×aboutボタンのリンクのクラス名が正しくありません',
    after_sign_in_message: '×ログイン後のヘッダーリンクが正しくありません。クラス名を確認してください',
    after_logout_link: '×ログアウト後にログインのリンクが表示されていません',
    after_logout_headers: '×ログイン後のリダイレクト先のヘッダーのクラス名を確認してください',
    after_logout_redirect: '△ログアウト後のリダイレクト先が間違えています',
    after_book_create_links: '×本の新規稿後に詳細画面に遷移していません。編集・削除ボタンが表示されていません',
    book_create: '×本の新規投稿ができません',
    book_edit: '×本の編集できません',
    book_edit_form: '×編集画面のフォームのクラス名、submitボタンを確認してください(※<button>タグ送信ボタンを記述している場合は、Railsのフォームの書き方でsubmitの記述に変更して下さい)',
    book_form_body: '×感想フォームに入力した内容が保存されていません',
    book_form_title: '×タイトル用のテキストボックスがありません。formやclass名を確認して下さい',
    book_save: '×投稿内容が保存できません',
    book_destroy: '×本の削除ができません',
    book_show_destroy_link: '×詳細画面の削除ボタンのクラス名が正しくありません、または詳細画面に遷移できないため削除のテストができません',
    book_correct_user: '×投稿したユーザー以外が本の編集ができてしまいます。投稿したユーザーのみ編集・削除できるように制限してください',
    book_index_show_link: '×本の一覧画面の詳細画面に遷移するリンクのクラス名が正しくありません',
    book_edit_link: '×本の編集リンクのクラス名が正しくない、または本の詳細画面に遷移できないため編集のテストができません',
    book_form_class: '×本の投稿フォームのクラス名、submitボタンを確認してください',
    book_destroy_test: '×本の削除のテストができません',
    book_submit_button: '×submitタグが確認できません。本の投稿フォームを確認して下さい',
    error_message: '×バリデーションのエラーメッセージが表示されません',
    empty_error_message: '×空欄投稿後のエラーメッセージをつけるとさらに良いです',
    fail_test: '※本の詳細画面に遷移できなかったため、このテストは実行できません',
    fail_to_authenticate_user: '×ユーザーのコントローラーに、ログイン済ユーザーのみがアクセスを許可できる制限をつけてください',
    home_button: '×homeボタンのリンクのクラス名が正しくありません',
    logout_class_name: '×ログアウトリンクのクラス名が正しくありません',
    // logout: '×ログアウトできません',
    login_header_home: '×ログイン後のヘッダーのHomeのクラス名が間違えています',
    login_success_message: '×ログインのサクセスメッセージをつけましょう',
    no_image: '×デフォルトの画像が設定されていない、またはプロフィールの画像が表示されていません',
    no_success_message: '×サクセスメッセージをつけましょう',
    no_table_tag: '×一覧ページの表は、テーブルタグを使用して作成してください',
    not_found_action_links: '×編集・削除のリンクが見つかりません',
    root_path_error: '×ルートパスの設定をしましょう',
    sign_in_button: '×sing inボタンのリンクのクラス名が正しくありません',
    sign_up_button: '×sign upボタンのリンクのクラス名が正しくありません',
    top_page_links: '×トップページに各種リンクがありません',
    test_stop_message: '×上記のテストの途中でエラーになりました。該当するテストの処理やclass名・スペルミス・変数を定義しているかもう一度確認してから再提出して下さい。',
    top_page_links: '×トップページに各種リンクがありません',
    top_page: '×トップページが作成されていません',
    user_page: '×ユーザーの新規登録画面に遷移できませんでした',
    user_form_class_name: '×ユーザー新規登録のフォームに正しいクラス名をつけてください',
    user_edit_class_name: '×ユーザー編集のリンクのクラス名が正しくありません',
    user_edit: '×ユーザーの編集内容が正しく編集できません',
    user_index: '×ユーザー一覧画面のユーザーの詳細画面に遷移するリンクが間違えています',
    user_show: '×ユーザーの詳細画面が正しく表示されていません',
    user_validates_error: '×バリデーションが正しく設定されていません',

    // サクセスメッセージ(A-Z順)-----------------------------------------//
    about: '◯ヘッダーのaboutが作成されています',
    default_image: '◯デフォルトの画像が設定されています',
    edit_user_form: '◯ユーザー編集フォームが正しく作成されています',
    edit_user_form_submit: '◯ユーザーの編集内容を送信しました',
    home: '◯ヘッダーのhomeが作成されています',
    new_user_form: '◯ユーザーの新規登録のフォームが作成されています',
    sign_in: '◯ヘッダーのsign_inが作成されています',
    sign_up: '◯ヘッダーのsign_upが作成されています',
    success_error_message: '◯エラーメッセージが表示されます',
    success_book_destroy: '件目の投稿を削除しました',
    success_message: '◯サクセスメッセージが表示されます',
    success_after_logout_redirect: '◯ログアウト後に正しくリダイレクトされます',
    success_user_edit: '◯ユーザーの編集内容が表示されています',
    success_book_create: '◯本の新規投稿ができます',
    success_repeat_book_create: '件目の本の新規投稿ができます',
    success_book_show: '◯本の詳細画面が正しく作成されています',
    success_correct_user: '◯投稿したユーザーのみが編集・削除できます',
    success_user_show: '◯ユーザーの詳細画面が正しく表示されています',
    success_user_validates:'◯ユーザーのバリデーションの設定がされています',
    top_header: '◯トップページのヘッダーが正しく作成されています',
    table_tag: '◯テーブルタグが使用されています',

    // 注意メッセージ(A-Z順)---------------------------------------------- //
    used_class: '⚠︎該当のフォーム以外にもclassが指定されている可能性があります'
};